name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.8.4+4
  cloud_firestore: ^0.9.13+1
  firebase_core: ^0.3.4
  modal_progress_hud: ^0.1.3
  animated_text_kit: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
  - images/
